''' <summary>
''' Field values present in an XC2 save file.
''' </summary>
Public Enum XC2DataType
    Rupees
    Materials_1
    Materials_2
    Materials_3
    Materials_4
    Materials_5
    Materials_6
    Materials_7
    Materials_8
    Materials_9
    Materials_10
    Materials_11
    Materials_12
    Materials_13
    Materials_14
    Materials_15
    Materials_16
    Materials_17
    Materials_18
    Materials_19
    Materials_20
    Materials_21
    Materials_22
    Materials_23
    Materials_24
    Materials_25
    Materials_26
    Materials_27
    Materials_28
    Materials_29
    Materials_30
    Materials_31
    Materials_32
    Materials_33
    Materials_34
    Materials_35
    Materials_36
    Materials_37
    Materials_38
    Materials_39
    Materials_40
    Materials_41
    Materials_42
    Materials_43
    Materials_44
    Materials_45
    Materials_46
    Materials_47
    Materials_48
    Materials_49
    Materials_50
    Materials_51
    Materials_52
    Materials_53
    Materials_54
    Materials_55
    Materials_56
    Materials_57
    Materials_58
    Materials_59
    Materials_60
    Materials_61
    Materials_62
    Materials_63
    Materials_64
    Materials_65
    Materials_66
    Materials_67
    Materials_68
    Materials_69
    Materials_70
    Materials_71
    Materials_72
    Materials_73
    Materials_74
    Materials_75
    Materials_76
    Materials_77
    Materials_78
    Materials_79
    Materials_80
    Materials_81
    Materials_82
    Materials_83
    Materials_84
    Materials_85
    Materials_86
    Materials_87
    Materials_88
    Materials_89
    Materials_90
    Materials_91
    Materials_92
    Materials_93
    Materials_94
    Materials_95
    Weapon_ID
    Weapon_Strength
    Weapon_Level
    Weapon_Skill
    Weapon_Set_As_03
    Character_1
    Character_2
    Character_3
    Character_4
    Character_5
    Character_6
    Character_7
    Character_8
    Character_9
    Character_10
    Character_11
    Character_12
    Character_13
    Character_14
    Character_15
    Character_16
    Character_17
    Character_18
    Character_19
    Character_20
    Character_21
    Character_22
    Character_23
    Character_24
    Character_25
    Character_26
    Character_27
    Character_28
    Character_29


End Enum

